### ISSUE TITLE
Feature: Open in sidebar

### ISSUE THREAD

**Issue by magi44ken** [brunobraga95/vertical-tabs-view#4]
Is it possible to add another option to show the vertical tabs in the sidebar panel instead as a popup list? If possible, add the following related features:

- Default Setting to select: popup list or sidebar panel.
- Keyboard Shortcut to hide or show sidebar panel.
- Keyboard Shortcut to select Vertical Tab View tab. Maybe this can be integrated into the show hide keyboard shortcut.
- Mouse wheel scrolling on the sidebar panel if mouse hover over sidebar panel.

Chrome have side panel that you can use to add Vertical Tab View to by turning on this flag.

- Side Panel: Enable

Chrome also have Search Side Panel flag.

- Side Search: Enable
- Side Search DSE: Enable

**Comment by brunobraga95** [comment]
Hi there, thanks for your request.

Chrome extensions are not integrated with the side panel, therefore it's not possible to achieve that :/

Feel free to open other issue if there is anything if can help you with. It makes me glad to know the extension is being used.
